name: run_tests

on:
  push:
    branches:
      - "*"

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install dependencies
        run: sudo apt-get install -y valgrind
      - name: test
        run: ./autotest.sh
